"""add tag table and shipping_tag mapping table

Revision ID: 801b01ff7d2e
Revises: 5df8da8eba33
Create Date: 2026-05-06 15:15:58.433486

"""
from datetime import datetime
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '801b01ff7d2e'
down_revision: Union[str, Sequence[str], None] = '5df8da8eba33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tag_table = op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('name', sa.Enum('express', 'same_day', 'priority', 'fragile', 'handle_with_care', 'keep_upright', 'temperature_controlled', 'perishable', 'high_value', 'insured', 'signature_required', 'hazardous', 'flammable', 'medical', 'pharmaceutical', 'gift', name='tagname'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    op.bulk_insert(
        tag_table,
        [
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "express",
                "description": "Express delivery",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "same_day",
                "description": "Same day delivery",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "priority",
                "description": "High priority shipment",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "fragile",
                "description": "Fragile item, handle with care",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "handle_with_care",
                "description": "Requires careful handling",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "keep_upright",
                "description": "Must be kept upright",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "temperature_controlled",
                "description": "Temperature controlled shipment",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "perishable",
                "description": "Perishable goods",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "high_value",
                "description": "High value shipment",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "insured",
                "description": "Shipment is insured",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "signature_required",
                "description": "Signature required on delivery",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "hazardous",
                "description": "Contains hazardous material",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "flammable",
                "description": "Flammable contents",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "medical",
                "description": "Medical shipment",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "pharmaceutical",
                "description": "Pharmaceutical items",
            },
            {
                "id": uuid.uuid4(),
                "created_at": datetime.now(),
                "name": "gift",
                "description": "Gift shipment",
            },
        ],
    )

    op.create_table('shipmenttag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipmenttag')
    op.drop_table('tag')
    # ### end Alembic commands ###
