"""add client_contact columns to shipment table

Revision ID: a9187f59bf53
Revises: 43fdd5565fe8
Create Date: 2026-05-01 12:35:18.595866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a9187f59bf53'
down_revision: Union[str, Sequence[str], None] = '43fdd5565fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('client_contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contact_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
