"""add Location table and a many-to-many relationship to it with DeliveryPartner table

Revision ID: f6ac51ca0750
Revises: 801b01ff7d2e
Create Date: 2026-05-08 17:22:06.759906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f6ac51ca0750'
down_revision: Union[str, Sequence[str], None] = '801b01ff7d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zip_code')
    )
    op.create_table('serviceable_location',
    sa.Column('delivery_partner_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_partner_id'], ['delivery_partner.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.zip_code'], ),
    sa.PrimaryKeyConstraint('delivery_partner_id', 'location_id')
    )
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_table('serviceable_location')
    op.drop_table('location')
    # ### end Alembic commands ###
