"""updated email column to be unique in user models

Revision ID: f8f12407c2b0
Revises: ac8bbd340f01
Create Date: 2026-05-04 15:43:05.845749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f8f12407c2b0'
down_revision: Union[str, Sequence[str], None] = 'ac8bbd340f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'delivery_partner', ['email'])
    op.create_unique_constraint(None, 'seller', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='unique')
    op.drop_constraint(None, 'delivery_partner', type_='unique')
    # ### end Alembic commands ###
